easy_admin:
    entities:
        Students:
            class: App\Entity\Student
            new:
                actions: ["import"]
            templates:
                list: 'admin/customizations/customer_list.html.twig'
