easy_admin:
    entities:
        Students:
            class: App\Entity\Student
            list:
                actions: ["import"]
            templates:
                list: 'admin/customizations/student_list.html.twig'
